### ISSUE TITLE
内存泄漏？

### ISSUE THREAD

**Issue by godwasdog** [lightsocks/lightsocks-java#1]
客户端的错误，内存泄露？

io.netty.util.ResourceLeakDetector reportLeak
严重: LEAK: ByteBuf.release() was not called before it's garbage-collected. Enab
le advanced leak reporting to find out where the leak occurred. To enable advanc
ed leak reporting, specify the JVM option '-Dio.netty.leakDetectionLevel=advance
d' or call ResourceLeakDetector.setLevel()﻿

服务器上用了一会就内存就占用15m了
openjdk-7-jdk编译

**Comment by godwasdog** [comment]
改java 1.8编译一样的错误。服务器一样错误

**Comment by lightsocks** [comment]
恩，跟JDK版本没关系，已经修复
